### ISSUE TITLE
Problems with 1st channel

### ISSUE THREAD

**Issue by MacBerger** [jpajala/ppm-mixer#1]
Hello jpajala,

I'm looking to contact you, I used your project as PPM mixer for my Graupner MX-16s with DIY Headtracker (also arduino-based), and it works great, except one case. When I "zero" the headtracker, sometimes this causes to omit the 1st channel from the transmitter, and put there middle value from now on. All other channels from the transmitter are copied fine. Nothing besides restarting arduino-mixer works.

Best Regards
Mac Berger

**Comment by jpajala** [comment]
Hi,

Thanks for the feedback.

Sorry but I have no idea what is going on there. What does the "zero the
headtracker" do?
Does the signal from the headtracker get broken for some time during the
zeroing?

--Jussi

**Comment by MacBerger** [comment]
Hi, thanks for your reply! :)

Yes, I think, that at some point the signal is broken, What's more - at the time of the break the code prints to the serial number "9" at PRINT(*idx) line below: (I have 8 channels from transmitter, 8 from HT, and 8 for output)

inline void addPulseToArray(const uint8_t* ppmMap, uint8_t* idx, bool* validStreamIdx, uint16_t pt, uint16_t pf, bool isI1, uint8_t expectedPulsesPerStream)
{
  // is input capture timer pulse, or change interrupt pulse
  
  uint8_t newIdx = (ppmMap == NULL?*idx:ppmMap[*idx]);
  
  // if the full pulse length exceeds a certain value, we know that this is the "reset" pulse.
  if(pf > PPM_STREAM_RESET_FULL_TIMEOUT)
  {
    if(expectedPulsesPerStream != *idx)
    {
      *validStreamIdx = false; // invalidate the pulses.
      PRINT(*idx);
    }

**Comment by jpajala** [comment]
Hi,

I can see one possible problem with a pulse stream that doesn't contain correct number of pulses. Reading the ppmMap the index might overflow causing erroneous masking the first channel away. 

I made some changes to the code, please see this branch:
https://github.com/jpajala/ppm-mixer/tree/ppmMapOverflowFix

NOTE: I have not tested this at all, just made sure it compiles. If you have time to test it, I would be happy to hear if the fix worked or not.

Another way to fix it, would be to reset your headtracker in a way that it keeps outputting the pulse stream in a correct fashion, keeping a pause after 8 channels have been outputted (or what ever is the number of channels you have there). Just speculation / educated guess :)

**Comment by MacBerger** [comment]
You are awesome!

It worked perfectly :)
Thank you. And since github doesn't allow contacting you directly - can you email me at this address (disposable), so we can mail in private: apzs (at) ucupdong.ml
